# Generated by Django 5.1.1 on 2024-11-01 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_downloaded', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
